# Generated by Django 6.0.3 on 2026-03-08 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('workspaces', '0002_setup_default_workspaces'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_user_id_3cbd31_idx',
            old_name='projects_pr_user_id_3f5a2b_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_user_id_40c3f7_idx',
            old_name='projects_pr_user_id_7d2c1a_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_client__e354a9_idx',
            old_name='projects_pr_client__8a4f3c_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_user_id_0a328a_idx',
            old_name='projects_pr_user_id_5c7e2d_idx',
        ),
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace, do kterého projekt patří', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='workspaces.workspace'),
        ),
    ]
