# Generated by Django 6.0.3 on 2026-03-08 16:18

from django.db import migrations


def populate_project_workspaces(apps, schema_editor):
    """Set workspace FK for existing projects from their owner's default workspace."""
    Project = apps.get_model('projects', 'Project')
    Workspace = apps.get_model('workspaces', 'Workspace')

    for project in Project.objects.filter(workspace__isnull=True):
        workspace = Workspace.objects.filter(owner=project.user).first()
        if workspace:
            project.workspace = workspace
            project.save(update_fields=['workspace'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_projects_pr_user_id_3f5a2b_idx_projects_pr_user_id_3cbd31_idx_and_more'),
        ('workspaces', '0002_setup_default_workspaces'),
    ]

    operations = [
        migrations.RunPython(
            populate_project_workspaces,
            migrations.RunPython.noop,
        ),
    ]
