# Generated by Django 6.0.2 on 2026-03-17 15:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0003_populate_workspace"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkCommit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("description", models.CharField(blank=True, default="", max_length=100)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_commits",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_commits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workcommits_workcommit",
                "ordering": ["-start_time"],
                "indexes": [
                    models.Index(
                        fields=["user", "-start_time"], name="workcommits_user_id_5bacf7_idx"
                    ),
                    models.Index(
                        fields=["user", "end_time"], name="workcommits_user_id_9b97e0_idx"
                    ),
                    models.Index(
                        fields=["project", "-start_time"], name="workcommits_project_239910_idx"
                    ),
                ],
            },
        ),
    ]
