# Generated by Django 6.0.3 on 2026-03-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workcommits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workcommit",
            name="tag",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
