# Generated by Django 6.0.3 on 2026-03-08 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('workspaces', '0002_setup_default_workspaces'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='client',
            new_name='clients_cli_user_id_ebd3f8_idx',
            old_name='clients_cl_user_id_24a1f5_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='clients_cli_user_id_822da7_idx',
            old_name='clients_cl_user_id_7d2a3b_idx',
        ),
        migrations.AddField(
            model_name='client',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace, do kterého klient patří', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='workspaces.workspace'),
        ),
    ]
