# Generated by Django 6.0.3 on 2026-03-08 16:18

from django.db import migrations


def populate_client_workspaces(apps, schema_editor):
    """Set workspace FK for existing clients from their owner's default workspace."""
    Client = apps.get_model('clients', 'Client')
    Workspace = apps.get_model('workspaces', 'Workspace')

    for client in Client.objects.filter(workspace__isnull=True):
        workspace = Workspace.objects.filter(owner=client.user).first()
        if workspace:
            client.workspace = workspace
            client.save(update_fields=['workspace'])


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_clients_cl_user_id_24a1f5_idx_clients_cli_user_id_ebd3f8_idx_and_more'),
        ('workspaces', '0002_setup_default_workspaces'),
    ]

    operations = [
        migrations.RunPython(
            populate_client_workspaces,
            migrations.RunPython.noop,
        ),
    ]
