# Generated by Django 6.0.2 on 2026-03-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0003_populate_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="hourly_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Výchozí hodinová sazba pro klienta",
                max_digits=8,
            ),
        ),
    ]
