# Generated by Django 6.0.3 on 2026-03-08 16:17

import uuid

from django.db import migrations
from django.utils.text import slugify


def create_default_workspaces(apps, schema_editor):
    """
    For each existing user, create a default workspace and membership.
    This ensures backward compatibility when transitioning to multi-tenant.
    """
    User = apps.get_model('users', 'User')
    Workspace = apps.get_model('workspaces', 'Workspace')
    Membership = apps.get_model('workspaces', 'WorkspaceMembership')

    for user in User.objects.all():
        slug = slugify(user.email.split('@')[0]) or 'workspace'
        base_slug = slug
        counter = 1
        while Workspace.objects.filter(slug=slug).exists():
            slug = f'{base_slug}-{counter}'
            counter += 1

        ws = Workspace.objects.create(
            id=uuid.uuid4(),
            name=f'{user.email} Workspace',
            slug=slug,
            owner=user,
        )
        Membership.objects.create(
            id=uuid.uuid4(),
            workspace=ws,
            user=user,
            role='owner',
        )


def reverse_default_workspaces(apps, schema_editor):
    """Remove all auto-created workspaces."""
    Workspace = apps.get_model('workspaces', 'Workspace')
    Workspace.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_default_workspaces,
            reverse_default_workspaces,
        ),
    ]
